### ISSUE TITLE
Review UI Mockup v2

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#123]
## Tasks

- Review [mockup v2](https://www.figma.com/file/yAeIrg6Whc8Bqj2EnG4MWP/Challenge-Registry) in Figma
- Comment in this [Google doc](https://docs.google.com/document/d/1m3Q3me5Q1DPcuzk1XQFykNTu6ugab06Ex3nyUI-QxlE/edit#)

Deadline: April 4 EOD

**Comment by rrchai** [comment]
Search:
- I think we could implement the layout and position where search bar and sort bar places, as well as the collapsable feature on the filter boxes. 
- I also agree with @vpchung to use one date picker to filter time. Or we put the "this year/last year" filters to the sort bar. @tschaffter you can make the call. 
- I think we could name ongoing differently, something like benchmarking or post-analysis. I guess there are currently not many challenges are in this phase, so we could either do a quick change on schema and data, or we just stick with active for now.
- @tschaffter Could we decide what information are essential/minimal to have on the challenge card? I like the what @vpchung has already, but I would add some numbers/stats (one/all of participants, submissions, stargazers) and the platform logo. The platform logo can be embedded in the banner, like what [kaggle](https://www.kaggle.com/competitions) does. I think the end goal is to attract users to click and go to the challenge detail page (because they cannot participate until they go to the challenge detail page) or make them stay on our web a bit longer ~

**Comment by rrchai** [comment]
### Challenge Detail:
- @vpchung Is the avatar on challenge detail page is coming from its banner?
- add challenge stargazers and favorite button? We could do similar way in [user profile](https://test.challenge-registry.org/tschaffter) - show number of stargazers; click to see what are they
- overall, I like the layout of @vpchung's design on this page, especially how the status label is embedded in the avatar

**Comment by tschaffter** [comment]
It looks like the above feedback from Rong have been moved to the [Google doc](https://docs.google.com/document/d/1m3Q3me5Q1DPcuzk1XQFykNTu6ugab06Ex3nyUI-QxlE/edit#).
