### ISSUE TITLE
Explore devcontainer CLI

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#168]
@rrchai Can you briefly describe what you know about the `devcontainer` CLI in this ticket?

**Comment by rrchai** [comment]
To install devcontainer cli via VSCodes:
![install](https://user-images.githubusercontent.com/73901500/167854999-38787930-1198-4df1-8eae-00686d7ee11d.png)

If you like to open devcontainer directly from the console (instead of using green button from vscodes):
```console
devcontainer open .
```
^ It will automatically open VSCodes and open the devcontainer of specified folde (similar to the `code .`, but use `devcontainer open` instead).

I haven't tried other commands of devcontainer cli. [Here](https://code.visualstudio.com/docs/remote/devcontainer-cli) is the official documents if needed.

**Comment by tschaffter** [comment]
Thanks for sharing! The CLI only supports two actions: open a folder in the devcontainer and build a devcontainer.
