### ISSUE TITLE
Pre-push test output doesn't allow to identify the projects whose test failed

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/challenge-registry#210]
The pre-push hook runs the command `yarn affected:test`, which translates to `nx affected:test` (see folder `./husky`). Running the tests of the affected code before pushing must be done as fast as possible, which is why the affected projects are tested in parallel. The issue is that the output printed to stdout is scrambled and does not include a summary table as `nx run-many --all --target=test` does.

The ideal solution would be to use an Nx flag that generate a summary table that enables to identify the projects that failed after running the pre-post hook while still keeping the benefit of affected projects in parallel.

**Comment by rrchai** [comment]
As I tested just now, if the nx caches are enabled, the output of pre-push hook will be able to print out which project is failed (e.g. `x nx run challenge-registry-challenges`) and also print out the summary of errors. Thus, this issue is not a big concern anymore and we could cycle back if there are follow-up issues.

**Comment by tschaffter** [comment]
@rrchai Nx Cloud solves this issue because it's easy to identify the task that failed there and quickly access only the relevant logs. Yet, the ideal solution would be purely a local one.

Example: https://nx.app/runs/zTaS6Hlm5oz
